AU Pongratz-Leisten, Beate
Y 2011
T "Divine Agency and Astralization of the Gods in Ancient Mesopotamia"
P in B. Pongratz Leisten (ed), *Reconsidering the Concept of Revolutionary Monotheism*, Winona Lake: Eisenbrauns, pp. 137-187.


@@@ R
SA sE
SD July 2020
TO anthropomorphism; divine agency; unity

Pongratz-Leisten's ambitious goal in this article is to investigate the construct of divine agency as it was conceived in Mesopotamia, with the purpose of explaining the role of anthropomorphism in that polytheistic conception of the divine. In order to achieve this goal, the scholar starts by discussing the notion of 'person' in ancient Mesopotamia, then defines the nature of the divine in Mesopotamia. In the second part of the article, she provides a description of the nature of divine agency and examines the astralization and solarization of gods.

By asking 'what is divine' rather than 'what is meant by a god' in ancient Mesopotamia, Pongratz-Leisten extends the notion of the divine beyond an anthropomorphic agent, while considering the possibility that agency could be extended to anything that possesses divine quality. In her opinion, the cosmos in the ancient near East was not considered as inherently divine nor unified. Gods were more than personifications of forces or parts of nature: they had the power to control and intervene over their respective realms, acting with intention and of their own will. The scholar applies the methodology and theories offered by cognitive science to ancient Near Eastern religion, thus finding an explanation for the identification of an agency even within inanimate and invisible beings. She distinguishes between the deity - being the primary agent - and his/her indices of presence (statues, symbols, or a celestial body) - i.e., the secondary agents.

Anthropomorphism, in this perspective, <<mediates between the divinity as primary agent and his or her secondary agents.>> (p. 147) Pongratz-Leisten also offers her own definition of religion, as <<a system of thought and action for interpreting and influencing the world, built on anthropomorphic and animistic premises.>> (p. 147)

In the second part of the article, the author describes why, in her opinion, astralization and solarization must be viewed as two distinct cultural strategies within the civilizations of the ancient Near East. On one side, solarization of human and divine kingship was generated by the political demand of territorial expansion, which asked for a new image of rulership claiming universal control. The astralization of the gods, instead, must be interpreted as a theological attempt to express divine supreme control over the universe - a need which occurred against the backdrop of the rise of astronomy as a science and ought to be considered a product of the professional elites with whom it was linked.


@NOTES R/22.1
NA jJL
ND January 2021

See {B}R/Pongratz-Leisten2011DivineAgency for an interpretation of divine agency and subjectivity.